name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: make build
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: |
            build/homebot-darwin-arm64
            build/homebot-linux-amd64
            
