name: Go

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: make build
      
    - name: Run latest-tag
      uses: EndBug/latest-tag@latest

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: |
            build/homebot-darwin-arm64
            build/homebot-linux-amd64

    - name: Latest Release
      uses: softprops/action-gh-release@v1
      with:
          tag_name: latest
          files: |
            build/homebot-darwin-arm64
            build/homebot-linux-amd64
            
